### ISSUE TITLE
Spread operator over string is not supported on device

### ISSUE THREAD

**Issue by reedyrm** [retyui/react-native-confirmation-code-field#23]
I'm running into an issue in production with the library with the following stack trace.

```
TypeError: Invalid attempt to spread non-iterable instance
  at taggedTemplateLiteralLoose(node_modules/react-native/Libraries/polyfills/babelHelpers.js:498:23)
  at toConsumableArray(node_modules/react-native/Libraries/polyfills/babelHelpers.js:568:14)
  at onChangeText(node_modules/react-native-confirmation-code-field/src/components/ConfirmationCodeInput/ConfirmationCodeInput.js:222:28)
  at onChangeText(node_modules/react-native-confirmation-code-field/src/components/TextInput/TextInput.js:16:47)
  at apply(node_modules/react-native/Libraries/Components/TextInput/TextInput.js:1119:43)
  at invokeGuardedCallbackImpl(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:47:10)
  at invokeGuardedCallback(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:65:29)
  at invokeGuardedCallbackAndCatchFirstError(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:78:25)
  at executeDispatch(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:172:3)
  at executeDispatchesAndReleaseTopLevel(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:221:9)
  at forEachAccumulated(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:205:59)
  at fn(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1065:8)
  at _batchedUpdatesImpl(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5841:12)
  at batchedUpdates(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1026:12)
  at _receiveRootNodeIDEvent(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1046:3)
  at getTime(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1083:5)
  at _this2(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:355:34)
  at DebuggerInternal(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:116:5)
  at flushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:312:14)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:17)
```

The source map shows that line 

`const newCodeSymbols = this.normalizeNewCode([...codeSymbols, ...text]);`

is failing.  I had canPasteCode=true and the user was able to type 2 characters into the same box which is when the error occurred.  It looks like the react-native polyfill doesn't see text as an iteratable array.  I'm not sure what version of javascript is running on the device, but its Android Samsung S7.

I was trying to replicate it on an emulator, but I'm not having much luck.  

Changing
```...text```
to
```...text.split()```
guarantees that that string is turned into a list of characters and copied into the new array.

**Comment by retyui** [comment]
rel: https://github.com/retyui/react-native-confirmation-code-field/issues/22

**Comment by retyui** [comment]
Thank you! :+1:

**Comment by reedyrm** [comment]
Thanks for getting in quickly!
